// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


class PaymentSessionRequest {
  PaymentSessionRequest({
    required this.sessionId,
    required this.initialUrl,
  });

  String sessionId;

  String initialUrl;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      initialUrl,
    ];
  }

  Object encode() {
    return _toList();  }

  static PaymentSessionRequest decode(Object result) {
    result as List<Object?>;
    return PaymentSessionRequest(
      sessionId: result[0]! as String,
      initialUrl: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PaymentSessionRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(initialUrl, other.initialUrl);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PaymentSessionRequest(sessionId: $sessionId, initialUrl: $initialUrl)';
  }
}

class PaymentSessionStatus {
  PaymentSessionStatus({
    required this.supported,
    this.message,
  });

  bool supported;

  String? message;

  List<Object?> _toList() {
    return <Object?>[
      supported,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static PaymentSessionStatus decode(Object result) {
    result as List<Object?>;
    return PaymentSessionStatus(
      supported: result[0]! as bool,
      message: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PaymentSessionStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(supported, other.supported) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PaymentSessionStatus(supported: $supported, message: $message)';
  }
}

class PaymentFillResult {
  PaymentFillResult({
    required this.success,
    required this.completedFields,
    required this.failedFields,
    this.message,
  });

  bool success;

  List<String> completedFields;

  List<String> failedFields;

  String? message;

  List<Object?> _toList() {
    return <Object?>[
      success,
      completedFields,
      failedFields,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static PaymentFillResult decode(Object result) {
    result as List<Object?>;
    return PaymentFillResult(
      success: result[0]! as bool,
      completedFields: (result[1]! as List<Object?>).cast<String>(),
      failedFields: (result[2]! as List<Object?>).cast<String>(),
      message: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PaymentFillResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(success, other.success) && _deepEquals(completedFields, other.completedFields) && _deepEquals(failedFields, other.failedFields) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PaymentFillResult(success: $success, completedFields: $completedFields, failedFields: $failedFields, message: $message)';
  }
}

class CheckoutBillingPayload {
  CheckoutBillingPayload({
    required this.pinyinName,
    required this.countryCode,
    required this.province,
    required this.city,
    required this.district,
    required this.pinyinCity,
    required this.pinyinDistrict,
    required this.addressLine1,
    required this.postalCode,
  });

  String pinyinName;

  String countryCode;

  String province;

  String city;

  String district;

  String pinyinCity;

  String pinyinDistrict;

  String addressLine1;

  String postalCode;

  List<Object?> _toList() {
    return <Object?>[
      pinyinName,
      countryCode,
      province,
      city,
      district,
      pinyinCity,
      pinyinDistrict,
      addressLine1,
      postalCode,
    ];
  }

  Object encode() {
    return _toList();  }

  static CheckoutBillingPayload decode(Object result) {
    result as List<Object?>;
    return CheckoutBillingPayload(
      pinyinName: result[0]! as String,
      countryCode: result[1]! as String,
      province: result[2]! as String,
      city: result[3]! as String,
      district: result[4]! as String,
      pinyinCity: result[5]! as String,
      pinyinDistrict: result[6]! as String,
      addressLine1: result[7]! as String,
      postalCode: result[8]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CheckoutBillingPayload || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(pinyinName, other.pinyinName) && _deepEquals(countryCode, other.countryCode) && _deepEquals(province, other.province) && _deepEquals(city, other.city) && _deepEquals(district, other.district) && _deepEquals(pinyinCity, other.pinyinCity) && _deepEquals(pinyinDistrict, other.pinyinDistrict) && _deepEquals(addressLine1, other.addressLine1) && _deepEquals(postalCode, other.postalCode);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CheckoutBillingPayload(pinyinName: $pinyinName, countryCode: $countryCode, province: $province, city: $city, district: $district, pinyinCity: $pinyinCity, pinyinDistrict: $pinyinDistrict, addressLine1: $addressLine1, postalCode: $postalCode)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is PaymentSessionRequest) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is PaymentSessionStatus) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is PaymentFillResult) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is CheckoutBillingPayload) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return PaymentSessionRequest.decode(readValue(buffer)!);
      case 130:
        return PaymentSessionStatus.decode(readValue(buffer)!);
      case 131:
        return PaymentFillResult.decode(readValue(buffer)!);
      case 132:
        return CheckoutBillingPayload.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Flutter 仅能调用这些固定命令；没有任意 JavaScript 执行接口。
class PaymentBrowserHostApi {
  /// Constructor for [PaymentBrowserHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PaymentBrowserHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<PaymentSessionStatus> createSession(PaymentSessionRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kiro_lucker.PaymentBrowserHostApi.createSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PaymentSessionStatus;
  }

  Future<bool> canGoBack(String sessionId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kiro_lucker.PaymentBrowserHostApi.canGoBack$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> goBack(String sessionId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kiro_lucker.PaymentBrowserHostApi.goBack$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> reload(String sessionId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kiro_lucker.PaymentBrowserHostApi.reload$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<PaymentFillResult> fillCheckout(String sessionId, CheckoutBillingPayload billing) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kiro_lucker.PaymentBrowserHostApi.fillCheckout$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, billing]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PaymentFillResult;
  }

  /// 停止页面、清理本次 profile/data store 后再释放 WebView。
  Future<void> closeSession(String sessionId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.kiro_lucker.PaymentBrowserHostApi.closeSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
