// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.kiroluker.kiro_lucker

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object PaymentBrowserApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * 原生 WebView 运行环境的只读事实，Dart 侧据此构造伪装标识。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BrowserEngineInfo (
  /** Android：WebView 默认 UA（解析引擎版本用）；iOS 为空串。 */
  val engineUserAgent: String,
  /** Android：Build.VERSION.RELEASE；iOS：UIDevice.systemVersion。 */
  val osVersion: String,
  /** Android：Build.MODEL；iOS："iPhone" 或 "iPad"。 */
  val deviceModel: String,
  /** Android：Build.ID；iOS 为 null。 */
  val buildId: String? = null,
  /** Android：如 "arm"（已按 UA-CH 惯例映射）；iOS 为 null。 */
  val architecture: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BrowserEngineInfo {
      val engineUserAgent = pigeonVar_list[0] as String
      val osVersion = pigeonVar_list[1] as String
      val deviceModel = pigeonVar_list[2] as String
      val buildId = pigeonVar_list[3] as String?
      val architecture = pigeonVar_list[4] as String?
      return BrowserEngineInfo(engineUserAgent, osVersion, deviceModel, buildId, architecture)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      engineUserAgent,
      osVersion,
      deviceModel,
      buildId,
      architecture,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BrowserEngineInfo
    return PaymentBrowserApiPigeonUtils.deepEquals(this.engineUserAgent, other.engineUserAgent) && PaymentBrowserApiPigeonUtils.deepEquals(this.osVersion, other.osVersion) && PaymentBrowserApiPigeonUtils.deepEquals(this.deviceModel, other.deviceModel) && PaymentBrowserApiPigeonUtils.deepEquals(this.buildId, other.buildId) && PaymentBrowserApiPigeonUtils.deepEquals(this.architecture, other.architecture)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.engineUserAgent)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.osVersion)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.deviceModel)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.buildId)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.architecture)
    return result
  }
  override fun toString(): String {
    return "BrowserEngineInfo(engineUserAgent=$engineUserAgent, osVersion=$osVersion, deviceModel=$deviceModel, buildId=$buildId, architecture=$architecture)"
  }
}

/**
 * UA-CH 品牌条目；只传结构化数据，注入脚本模板留在原生侧。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BrandVersion (
  val brand: String,
  val version: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BrandVersion {
      val brand = pigeonVar_list[0] as String
      val version = pigeonVar_list[1] as String
      return BrandVersion(brand, version)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      brand,
      version,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BrandVersion
    return PaymentBrowserApiPigeonUtils.deepEquals(this.brand, other.brand) && PaymentBrowserApiPigeonUtils.deepEquals(this.version, other.version)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.brand)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.version)
    return result
  }
  override fun toString(): String {
    return "BrandVersion(brand=$brand, version=$version)"
  }
}

/**
 * 支付 WebView 的浏览器伪装标识。全字段由 Dart 侧白名单模板生成，原生不执行透传脚本。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BrowserIdentity (
  val userAgent: String,
  val brands: List<BrandVersion>,
  val mobile: Boolean,
  val platform: String,
  val platformVersion: String? = null,
  val architecture: String? = null,
  val fullVersion: String,
  val model: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BrowserIdentity {
      val userAgent = pigeonVar_list[0] as String
      val brands = pigeonVar_list[1] as List<BrandVersion>
      val mobile = pigeonVar_list[2] as Boolean
      val platform = pigeonVar_list[3] as String
      val platformVersion = pigeonVar_list[4] as String?
      val architecture = pigeonVar_list[5] as String?
      val fullVersion = pigeonVar_list[6] as String
      val model = pigeonVar_list[7] as String?
      return BrowserIdentity(userAgent, brands, mobile, platform, platformVersion, architecture, fullVersion, model)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      userAgent,
      brands,
      mobile,
      platform,
      platformVersion,
      architecture,
      fullVersion,
      model,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BrowserIdentity
    return PaymentBrowserApiPigeonUtils.deepEquals(this.userAgent, other.userAgent) && PaymentBrowserApiPigeonUtils.deepEquals(this.brands, other.brands) && PaymentBrowserApiPigeonUtils.deepEquals(this.mobile, other.mobile) && PaymentBrowserApiPigeonUtils.deepEquals(this.platform, other.platform) && PaymentBrowserApiPigeonUtils.deepEquals(this.platformVersion, other.platformVersion) && PaymentBrowserApiPigeonUtils.deepEquals(this.architecture, other.architecture) && PaymentBrowserApiPigeonUtils.deepEquals(this.fullVersion, other.fullVersion) && PaymentBrowserApiPigeonUtils.deepEquals(this.model, other.model)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.userAgent)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.brands)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.mobile)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.platform)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.platformVersion)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.architecture)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.fullVersion)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.model)
    return result
  }
  override fun toString(): String {
    return "BrowserIdentity(userAgent=$userAgent, brands=$brands, mobile=$mobile, platform=$platform, platformVersion=$platformVersion, architecture=$architecture, fullVersion=$fullVersion, model=$model)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PaymentSessionRequest (
  val sessionId: String,
  val initialUrl: String,
  /** null 表示不做伪装，沿用系统默认 UA。 */
  val identity: BrowserIdentity? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PaymentSessionRequest {
      val sessionId = pigeonVar_list[0] as String
      val initialUrl = pigeonVar_list[1] as String
      val identity = pigeonVar_list[2] as BrowserIdentity?
      return PaymentSessionRequest(sessionId, initialUrl, identity)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sessionId,
      initialUrl,
      identity,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PaymentSessionRequest
    return PaymentBrowserApiPigeonUtils.deepEquals(this.sessionId, other.sessionId) && PaymentBrowserApiPigeonUtils.deepEquals(this.initialUrl, other.initialUrl) && PaymentBrowserApiPigeonUtils.deepEquals(this.identity, other.identity)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.sessionId)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.initialUrl)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.identity)
    return result
  }
  override fun toString(): String {
    return "PaymentSessionRequest(sessionId=$sessionId, initialUrl=$initialUrl, identity=$identity)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PaymentSessionStatus (
  val supported: Boolean,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PaymentSessionStatus {
      val supported = pigeonVar_list[0] as Boolean
      val message = pigeonVar_list[1] as String?
      return PaymentSessionStatus(supported, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      supported,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PaymentSessionStatus
    return PaymentBrowserApiPigeonUtils.deepEquals(this.supported, other.supported) && PaymentBrowserApiPigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.supported)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.message)
    return result
  }
  override fun toString(): String {
    return "PaymentSessionStatus(supported=$supported, message=$message)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PaymentFillResult (
  val success: Boolean,
  val completedFields: List<String>,
  val failedFields: List<String>,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PaymentFillResult {
      val success = pigeonVar_list[0] as Boolean
      val completedFields = pigeonVar_list[1] as List<String>
      val failedFields = pigeonVar_list[2] as List<String>
      val message = pigeonVar_list[3] as String?
      return PaymentFillResult(success, completedFields, failedFields, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      completedFields,
      failedFields,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PaymentFillResult
    return PaymentBrowserApiPigeonUtils.deepEquals(this.success, other.success) && PaymentBrowserApiPigeonUtils.deepEquals(this.completedFields, other.completedFields) && PaymentBrowserApiPigeonUtils.deepEquals(this.failedFields, other.failedFields) && PaymentBrowserApiPigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.success)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.completedFields)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.failedFields)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.message)
    return result
  }
  override fun toString(): String {
    return "PaymentFillResult(success=$success, completedFields=$completedFields, failedFields=$failedFields, message=$message)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CheckoutBillingPayload (
  val pinyinName: String,
  val countryCode: String,
  val province: String,
  val city: String,
  val district: String,
  val pinyinCity: String,
  val pinyinDistrict: String,
  val addressLine1: String,
  val postalCode: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CheckoutBillingPayload {
      val pinyinName = pigeonVar_list[0] as String
      val countryCode = pigeonVar_list[1] as String
      val province = pigeonVar_list[2] as String
      val city = pigeonVar_list[3] as String
      val district = pigeonVar_list[4] as String
      val pinyinCity = pigeonVar_list[5] as String
      val pinyinDistrict = pigeonVar_list[6] as String
      val addressLine1 = pigeonVar_list[7] as String
      val postalCode = pigeonVar_list[8] as String
      return CheckoutBillingPayload(pinyinName, countryCode, province, city, district, pinyinCity, pinyinDistrict, addressLine1, postalCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      pinyinName,
      countryCode,
      province,
      city,
      district,
      pinyinCity,
      pinyinDistrict,
      addressLine1,
      postalCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CheckoutBillingPayload
    return PaymentBrowserApiPigeonUtils.deepEquals(this.pinyinName, other.pinyinName) && PaymentBrowserApiPigeonUtils.deepEquals(this.countryCode, other.countryCode) && PaymentBrowserApiPigeonUtils.deepEquals(this.province, other.province) && PaymentBrowserApiPigeonUtils.deepEquals(this.city, other.city) && PaymentBrowserApiPigeonUtils.deepEquals(this.district, other.district) && PaymentBrowserApiPigeonUtils.deepEquals(this.pinyinCity, other.pinyinCity) && PaymentBrowserApiPigeonUtils.deepEquals(this.pinyinDistrict, other.pinyinDistrict) && PaymentBrowserApiPigeonUtils.deepEquals(this.addressLine1, other.addressLine1) && PaymentBrowserApiPigeonUtils.deepEquals(this.postalCode, other.postalCode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.pinyinName)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.countryCode)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.province)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.city)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.district)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.pinyinCity)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.pinyinDistrict)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.addressLine1)
    result = 31 * result + PaymentBrowserApiPigeonUtils.deepHash(this.postalCode)
    return result
  }
  override fun toString(): String {
    return "CheckoutBillingPayload(pinyinName=$pinyinName, countryCode=$countryCode, province=$province, city=$city, district=$district, pinyinCity=$pinyinCity, pinyinDistrict=$pinyinDistrict, addressLine1=$addressLine1, postalCode=$postalCode)"
  }
}
private open class PaymentBrowserApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BrowserEngineInfo.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BrandVersion.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BrowserIdentity.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PaymentSessionRequest.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PaymentSessionStatus.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PaymentFillResult.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CheckoutBillingPayload.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BrowserEngineInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is BrandVersion -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is BrowserIdentity -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PaymentSessionRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PaymentSessionStatus -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is PaymentFillResult -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is CheckoutBillingPayload -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Flutter 仅能调用这些固定命令；没有任意 JavaScript 执行接口。
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface PaymentBrowserHostApi {
  suspend fun createSession(request: PaymentSessionRequest): PaymentSessionStatus
  /** 读取 WebView 引擎与系统的只读信息，供 Dart 构造伪装 UA。 */
  suspend fun getBrowserEngineInfo(): BrowserEngineInfo
  suspend fun canGoBack(sessionId: String): Boolean
  suspend fun goBack(sessionId: String)
  suspend fun reload(sessionId: String)
  suspend fun fillCheckout(sessionId: String, billing: CheckoutBillingPayload): PaymentFillResult
  /** 停止页面、清理本次 profile/data store 后再释放 WebView。 */
  suspend fun closeSession(sessionId: String)

  companion object {
    /** The codec used by PaymentBrowserHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PaymentBrowserApiPigeonCodec()
    }
    /** Sets up an instance of `PaymentBrowserHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PaymentBrowserHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kiro_lucker.PaymentBrowserHostApi.createSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PaymentSessionRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.createSession(requestArg))
              } catch (exception: Throwable) {
                PaymentBrowserApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kiro_lucker.PaymentBrowserHostApi.getBrowserEngineInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getBrowserEngineInfo())
              } catch (exception: Throwable) {
                PaymentBrowserApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kiro_lucker.PaymentBrowserHostApi.canGoBack$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.canGoBack(sessionIdArg))
              } catch (exception: Throwable) {
                PaymentBrowserApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kiro_lucker.PaymentBrowserHostApi.goBack$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.goBack(sessionIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                PaymentBrowserApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kiro_lucker.PaymentBrowserHostApi.reload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.reload(sessionIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                PaymentBrowserApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kiro_lucker.PaymentBrowserHostApi.fillCheckout$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val billingArg = args[1] as CheckoutBillingPayload
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.fillCheckout(sessionIdArg, billingArg))
              } catch (exception: Throwable) {
                PaymentBrowserApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kiro_lucker.PaymentBrowserHostApi.closeSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.closeSession(sessionIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                PaymentBrowserApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
