// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum PaymentBrowserApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// 原生 WebView 运行环境的只读事实，Dart 侧据此构造伪装标识。
///
/// Generated class from Pigeon that represents data sent in messages.
struct BrowserEngineInfo: Hashable, CustomStringConvertible {
  /// Android：WebView 默认 UA（解析引擎版本用）；iOS 为空串。
  var engineUserAgent: String
  /// Android：Build.VERSION.RELEASE；iOS：UIDevice.systemVersion。
  var osVersion: String
  /// Android：Build.MODEL；iOS："iPhone" 或 "iPad"。
  var deviceModel: String
  /// Android：Build.ID；iOS 为 null。
  var buildId: String? = nil
  /// Android：如 "arm"（已按 UA-CH 惯例映射）；iOS 为 null。
  var architecture: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BrowserEngineInfo? {
    let engineUserAgent = pigeonVar_list[0] as! String
    let osVersion = pigeonVar_list[1] as! String
    let deviceModel = pigeonVar_list[2] as! String
    let buildId: String? = nilOrValue(pigeonVar_list[3])
    let architecture: String? = nilOrValue(pigeonVar_list[4])

    return BrowserEngineInfo(
      engineUserAgent: engineUserAgent,
      osVersion: osVersion,
      deviceModel: deviceModel,
      buildId: buildId,
      architecture: architecture
    )
  }
  func toList() -> [Any?] {
    return [
      engineUserAgent,
      osVersion,
      deviceModel,
      buildId,
      architecture,
    ]
  }
  static func == (lhs: BrowserEngineInfo, rhs: BrowserEngineInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PaymentBrowserApiPigeonInternal.deepEquals(lhs.engineUserAgent, rhs.engineUserAgent) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.osVersion, rhs.osVersion) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.deviceModel, rhs.deviceModel) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.buildId, rhs.buildId) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.architecture, rhs.architecture)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BrowserEngineInfo")
    PaymentBrowserApiPigeonInternal.deepHash(value: engineUserAgent, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: osVersion, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: deviceModel, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: buildId, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: architecture, hasher: &hasher)
  }

  public var description: String {
    return "BrowserEngineInfo(engineUserAgent: \(String(describing: engineUserAgent)), osVersion: \(String(describing: osVersion)), deviceModel: \(String(describing: deviceModel)), buildId: \(String(describing: buildId)), architecture: \(String(describing: architecture)))"
  }
}

/// UA-CH 品牌条目；只传结构化数据，注入脚本模板留在原生侧。
///
/// Generated class from Pigeon that represents data sent in messages.
struct BrandVersion: Hashable, CustomStringConvertible {
  var brand: String
  var version: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BrandVersion? {
    let brand = pigeonVar_list[0] as! String
    let version = pigeonVar_list[1] as! String

    return BrandVersion(
      brand: brand,
      version: version
    )
  }
  func toList() -> [Any?] {
    return [
      brand,
      version,
    ]
  }
  static func == (lhs: BrandVersion, rhs: BrandVersion) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PaymentBrowserApiPigeonInternal.deepEquals(lhs.brand, rhs.brand) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.version, rhs.version)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BrandVersion")
    PaymentBrowserApiPigeonInternal.deepHash(value: brand, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: version, hasher: &hasher)
  }

  public var description: String {
    return "BrandVersion(brand: \(String(describing: brand)), version: \(String(describing: version)))"
  }
}

/// 支付 WebView 的浏览器伪装标识。全字段由 Dart 侧白名单模板生成，原生不执行透传脚本。
///
/// Generated class from Pigeon that represents data sent in messages.
struct BrowserIdentity: Hashable, CustomStringConvertible {
  var userAgent: String
  var brands: [BrandVersion]
  var mobile: Bool
  var platform: String
  var platformVersion: String? = nil
  var architecture: String? = nil
  var fullVersion: String
  var model: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BrowserIdentity? {
    let userAgent = pigeonVar_list[0] as! String
    let brands = pigeonVar_list[1] as! [BrandVersion]
    let mobile = pigeonVar_list[2] as! Bool
    let platform = pigeonVar_list[3] as! String
    let platformVersion: String? = nilOrValue(pigeonVar_list[4])
    let architecture: String? = nilOrValue(pigeonVar_list[5])
    let fullVersion = pigeonVar_list[6] as! String
    let model: String? = nilOrValue(pigeonVar_list[7])

    return BrowserIdentity(
      userAgent: userAgent,
      brands: brands,
      mobile: mobile,
      platform: platform,
      platformVersion: platformVersion,
      architecture: architecture,
      fullVersion: fullVersion,
      model: model
    )
  }
  func toList() -> [Any?] {
    return [
      userAgent,
      brands,
      mobile,
      platform,
      platformVersion,
      architecture,
      fullVersion,
      model,
    ]
  }
  static func == (lhs: BrowserIdentity, rhs: BrowserIdentity) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PaymentBrowserApiPigeonInternal.deepEquals(lhs.userAgent, rhs.userAgent) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.brands, rhs.brands) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.mobile, rhs.mobile) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.platform, rhs.platform) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.platformVersion, rhs.platformVersion) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.architecture, rhs.architecture) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.fullVersion, rhs.fullVersion) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.model, rhs.model)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BrowserIdentity")
    PaymentBrowserApiPigeonInternal.deepHash(value: userAgent, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: brands, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: mobile, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: platform, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: platformVersion, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: architecture, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: fullVersion, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: model, hasher: &hasher)
  }

  public var description: String {
    return "BrowserIdentity(userAgent: \(String(describing: userAgent)), brands: \(String(describing: brands)), mobile: \(String(describing: mobile)), platform: \(String(describing: platform)), platformVersion: \(String(describing: platformVersion)), architecture: \(String(describing: architecture)), fullVersion: \(String(describing: fullVersion)), model: \(String(describing: model)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PaymentSessionRequest: Hashable, CustomStringConvertible {
  var sessionId: String
  var initialUrl: String
  /// null 表示不做伪装，沿用系统默认 UA。
  var identity: BrowserIdentity? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PaymentSessionRequest? {
    let sessionId = pigeonVar_list[0] as! String
    let initialUrl = pigeonVar_list[1] as! String
    let identity: BrowserIdentity? = nilOrValue(pigeonVar_list[2])

    return PaymentSessionRequest(
      sessionId: sessionId,
      initialUrl: initialUrl,
      identity: identity
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      initialUrl,
      identity,
    ]
  }
  static func == (lhs: PaymentSessionRequest, rhs: PaymentSessionRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PaymentBrowserApiPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.initialUrl, rhs.initialUrl) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.identity, rhs.identity)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PaymentSessionRequest")
    PaymentBrowserApiPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: initialUrl, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: identity, hasher: &hasher)
  }

  public var description: String {
    return "PaymentSessionRequest(sessionId: \(String(describing: sessionId)), initialUrl: \(String(describing: initialUrl)), identity: \(String(describing: identity)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PaymentSessionStatus: Hashable, CustomStringConvertible {
  var supported: Bool
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PaymentSessionStatus? {
    let supported = pigeonVar_list[0] as! Bool
    let message: String? = nilOrValue(pigeonVar_list[1])

    return PaymentSessionStatus(
      supported: supported,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      supported,
      message,
    ]
  }
  static func == (lhs: PaymentSessionStatus, rhs: PaymentSessionStatus) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PaymentBrowserApiPigeonInternal.deepEquals(lhs.supported, rhs.supported) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PaymentSessionStatus")
    PaymentBrowserApiPigeonInternal.deepHash(value: supported, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: message, hasher: &hasher)
  }

  public var description: String {
    return "PaymentSessionStatus(supported: \(String(describing: supported)), message: \(String(describing: message)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PaymentFillResult: Hashable, CustomStringConvertible {
  var success: Bool
  var completedFields: [String]
  var failedFields: [String]
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PaymentFillResult? {
    let success = pigeonVar_list[0] as! Bool
    let completedFields = pigeonVar_list[1] as! [String]
    let failedFields = pigeonVar_list[2] as! [String]
    let message: String? = nilOrValue(pigeonVar_list[3])

    return PaymentFillResult(
      success: success,
      completedFields: completedFields,
      failedFields: failedFields,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      completedFields,
      failedFields,
      message,
    ]
  }
  static func == (lhs: PaymentFillResult, rhs: PaymentFillResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PaymentBrowserApiPigeonInternal.deepEquals(lhs.success, rhs.success) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.completedFields, rhs.completedFields) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.failedFields, rhs.failedFields) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PaymentFillResult")
    PaymentBrowserApiPigeonInternal.deepHash(value: success, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: completedFields, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: failedFields, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: message, hasher: &hasher)
  }

  public var description: String {
    return "PaymentFillResult(success: \(String(describing: success)), completedFields: \(String(describing: completedFields)), failedFields: \(String(describing: failedFields)), message: \(String(describing: message)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CheckoutBillingPayload: Hashable, CustomStringConvertible {
  var pinyinName: String
  var countryCode: String
  var province: String
  var city: String
  var district: String
  var pinyinCity: String
  var pinyinDistrict: String
  var addressLine1: String
  var postalCode: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CheckoutBillingPayload? {
    let pinyinName = pigeonVar_list[0] as! String
    let countryCode = pigeonVar_list[1] as! String
    let province = pigeonVar_list[2] as! String
    let city = pigeonVar_list[3] as! String
    let district = pigeonVar_list[4] as! String
    let pinyinCity = pigeonVar_list[5] as! String
    let pinyinDistrict = pigeonVar_list[6] as! String
    let addressLine1 = pigeonVar_list[7] as! String
    let postalCode = pigeonVar_list[8] as! String

    return CheckoutBillingPayload(
      pinyinName: pinyinName,
      countryCode: countryCode,
      province: province,
      city: city,
      district: district,
      pinyinCity: pinyinCity,
      pinyinDistrict: pinyinDistrict,
      addressLine1: addressLine1,
      postalCode: postalCode
    )
  }
  func toList() -> [Any?] {
    return [
      pinyinName,
      countryCode,
      province,
      city,
      district,
      pinyinCity,
      pinyinDistrict,
      addressLine1,
      postalCode,
    ]
  }
  static func == (lhs: CheckoutBillingPayload, rhs: CheckoutBillingPayload) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PaymentBrowserApiPigeonInternal.deepEquals(lhs.pinyinName, rhs.pinyinName) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.countryCode, rhs.countryCode) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.province, rhs.province) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.city, rhs.city) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.district, rhs.district) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.pinyinCity, rhs.pinyinCity) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.pinyinDistrict, rhs.pinyinDistrict) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.addressLine1, rhs.addressLine1) && PaymentBrowserApiPigeonInternal.deepEquals(lhs.postalCode, rhs.postalCode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CheckoutBillingPayload")
    PaymentBrowserApiPigeonInternal.deepHash(value: pinyinName, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: countryCode, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: province, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: city, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: district, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: pinyinCity, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: pinyinDistrict, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: addressLine1, hasher: &hasher)
    PaymentBrowserApiPigeonInternal.deepHash(value: postalCode, hasher: &hasher)
  }

  public var description: String {
    return "CheckoutBillingPayload(pinyinName: \(String(describing: pinyinName)), countryCode: \(String(describing: countryCode)), province: \(String(describing: province)), city: \(String(describing: city)), district: \(String(describing: district)), pinyinCity: \(String(describing: pinyinCity)), pinyinDistrict: \(String(describing: pinyinDistrict)), addressLine1: \(String(describing: addressLine1)), postalCode: \(String(describing: postalCode)))"
  }
}

private class PaymentBrowserApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return BrowserEngineInfo.fromList(self.readValue() as! [Any?])
    case 130:
      return BrandVersion.fromList(self.readValue() as! [Any?])
    case 131:
      return BrowserIdentity.fromList(self.readValue() as! [Any?])
    case 132:
      return PaymentSessionRequest.fromList(self.readValue() as! [Any?])
    case 133:
      return PaymentSessionStatus.fromList(self.readValue() as! [Any?])
    case 134:
      return PaymentFillResult.fromList(self.readValue() as! [Any?])
    case 135:
      return CheckoutBillingPayload.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PaymentBrowserApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BrowserEngineInfo {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? BrandVersion {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? BrowserIdentity {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PaymentSessionRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PaymentSessionStatus {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PaymentFillResult {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? CheckoutBillingPayload {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PaymentBrowserApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PaymentBrowserApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PaymentBrowserApiPigeonCodecWriter(data: data)
  }
}

class PaymentBrowserApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PaymentBrowserApiPigeonCodec(readerWriter: PaymentBrowserApiPigeonCodecReaderWriter())
}


/// Flutter 仅能调用这些固定命令；没有任意 JavaScript 执行接口。
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PaymentBrowserHostApi {
  func createSession(request: PaymentSessionRequest) async throws -> PaymentSessionStatus
  /// 读取 WebView 引擎与系统的只读信息，供 Dart 构造伪装 UA。
  func getBrowserEngineInfo() async throws -> BrowserEngineInfo
  func canGoBack(sessionId: String) async throws -> Bool
  func goBack(sessionId: String) async throws
  func reload(sessionId: String) async throws
  func fillCheckout(sessionId: String, billing: CheckoutBillingPayload) async throws -> PaymentFillResult
  /// 停止页面、清理本次 profile/data store 后再释放 WebView。
  func closeSession(sessionId: String) async throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PaymentBrowserHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PaymentBrowserApiPigeonCodec.shared }
  /// Sets up an instance of `PaymentBrowserHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PaymentBrowserHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let createSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kiro_lucker.PaymentBrowserHostApi.createSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PaymentSessionRequest
        Task { @MainActor in
          do {
            let result = try await api.createSession(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      createSessionChannel.setMessageHandler(nil)
    }
    /// 读取 WebView 引擎与系统的只读信息，供 Dart 构造伪装 UA。
    let getBrowserEngineInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kiro_lucker.PaymentBrowserHostApi.getBrowserEngineInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBrowserEngineInfoChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.getBrowserEngineInfo()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getBrowserEngineInfoChannel.setMessageHandler(nil)
    }
    let canGoBackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kiro_lucker.PaymentBrowserHostApi.canGoBack\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      canGoBackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.canGoBack(sessionId: sessionIdArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      canGoBackChannel.setMessageHandler(nil)
    }
    let goBackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kiro_lucker.PaymentBrowserHostApi.goBack\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      goBackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.goBack(sessionId: sessionIdArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      goBackChannel.setMessageHandler(nil)
    }
    let reloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kiro_lucker.PaymentBrowserHostApi.reload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      reloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.reload(sessionId: sessionIdArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      reloadChannel.setMessageHandler(nil)
    }
    let fillCheckoutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kiro_lucker.PaymentBrowserHostApi.fillCheckout\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fillCheckoutChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let billingArg = args[1] as! CheckoutBillingPayload
        Task { @MainActor in
          do {
            let result = try await api.fillCheckout(sessionId: sessionIdArg, billing: billingArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      fillCheckoutChannel.setMessageHandler(nil)
    }
    /// 停止页面、清理本次 profile/data store 后再释放 WebView。
    let closeSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kiro_lucker.PaymentBrowserHostApi.closeSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.closeSession(sessionId: sessionIdArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeSessionChannel.setMessageHandler(nil)
    }
  }
}
